### ISSUE TITLE
Wrap insurance-bot-db into microservice

### ISSUE THREAD

**Issue by data-henrik** [IBM-Bluemix/cloudco-insurance#16]
The db is used by two repositories and created as service in the deploy scripts for bot and dashboard. Clean up the architecture and wrap the db into a service or manage dependencies in a different way.

**Comment by spearz** [comment]
I cant register a new user error given below 

PS C:\..\insurance-bot> npm start

> CloudCo@0.0.1 start C:\...\insurance-bot
> node app.js

[2018-08-14 10:51:35.306] [DEBUG] appid-public-key-util - Initializing
[2018-08-14 10:51:36.068] [DEBUG] appid-token-util - Initializing
[2018-08-14 10:51:36.201] [INFO] appid-sdk - Initialized
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
[2018-08-14 10:51:37.279] [DEBUG] appid-webapp-strategy - Initializing
[2018-08-14 10:51:37.280] [DEBUG] appid-webapp-strategy-config - Initializing
[2018-08-14 10:51:37.280] [INFO] appid-webapp-strategy-config - tenantId e297f9bf-7f18-4af7-9d60-4bf7b4c5d4d8
[2018-08-14 10:51:37.280] [INFO] appid-webapp-strategy-config - clientId 87132c0a-4cb6-40cb-bb3e-5b64014176f8
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - secret [NOT SHOWING]
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - oauthServerUrl https://appid-oauth.eu-gb.bluemix.net/oauth/v3/e297f9bf-7f18-4af7-9d60-4bf7b4c5d4d8
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - redirectUri http://localhost:6001/health
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - preferredLocale undefined
[2018-08-14 10:51:37.282] [INFO] self-service-manager - using user IAM API key [NOT SHOWING]
[2018-08-14 10:51:37.282] [INFO] self-service-manager - iamTokenUrl https://iam.bluemix.net/oidc/token
[2018-08-14 10:51:37.283] [INFO] self-service-manager - managementUrl https://appid-management.eu-gb.bluemix.net/management/v4/e297f9bf-7f18-4af7-9d60-4bf7b4c5d4d8
server starting on http://localhost:6001
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
{ url: 'https://gateway.watsonplatform.net/assistant/api',
  username: '0fa297ea-402a-43de-941a-f7e1229a0204',
  password: 'tetFinmvHGFA' }
No conversation workspace configured in the environment.
Looking for a workspace named 'Ana'...
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
Database already exists:  logs
Database already exists:  benefits
Using Watson Conversation with username 0fa297ea-402a-43de-941a-f7e1229a0204 and workspace 092e60fa-a041-4117-9768-b6d303911a42
GET /health 200 310.081 ms - 3002
GET /isLoggedIn 200 2.558 ms - 27
GET /favicon.ico 404 4.247 ms - 150
GET /signup 200 46.224 ms - 3145
GET /isLoggedIn 304 1.400 ms - -
[2018-08-14 10:53:06.092] [DEBUG] self-service-manager - Obtained IAM token: eyJraWQiOiIyMDE3MTAzMC0wMDowMDowMCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJpYW0tU2VydmljZUlkLWUyODVmN2EzLTNkMTAtNGRmYS1hYzU1LTFhZTZhZDljNmYyZSIsImlkIjoiaWFtLVNlcnZpY2VJZC1lMjg1ZjdhMy0zZDEwLTRkZmEtYWM1NS0xYWU2YWQ5YzZmMmUiLCJyZWFsbWlkIjoiaWFtIiwiaWRlbnRpZmllciI6IlNlcnZpY2VJZC1lMjg1ZjdhMy0zZDEwLTRkZmEtYWM1NS0xYWU2YWQ5YzZmMmUiLCJzdWIiOiJTZXJ2aWNlSWQtZTI4NWY3YTMtM2QxMC00ZGZhLWFjNTUtMWFlNmFkOWM2ZjJlIiwic3ViX3R5cGUiOiJTZXJ2aWNlSWQiLCJhY2NvdW50Ijp7ImJzcyI6IjQyMDNhN2MxMTQzYzQ0N2ViMzgxMWQxMTAxMGM2OGRhIn0sImlhdCI6MTUzNDIzMzE4MiwiZXhwIjoxNTM0MjM2NzgyLCJpc3MiOiJodHRwczovL2lhbS5uZy5ibHVlbWl4Lm5ldC9vaWRjL3Rva2VuIiwiZ3JhbnRfdHlwZSI6InVybjppYm06cGFyYW1zOm9hdXRoOmdyYW50LXR5cGU6YXBpa2V5Iiwic2NvcGUiOiJpYm0gb3BlbmlkIiwiY2xpZW50X2lkIjoiZGVmYXVsdCIsImFjciI6MSwiYW1yIjpbInB3ZCJdfQ.FylahSS0uCeNgADKH0_I_TkxFENVuRHUBt3YB1I955pM4GGmryeMNwCl9azgrOpnW2JY8oog-nLKxY1k4VKO6fNK_PjDW0El5atgBXHQqO-28DCJaZA3WLFn2exSFjeaTp7R5jy9radpXcyf-P-uIZR_0q3ramMQtg5Zaz-pBDE8S6_cH04Y5GvJ5FSh3JnIML-tsFkHyRfFqQ84bD1cZZtb9uWMLjjicuEKHkvgrdsD_c9njoyH2RxHIJ6yrHPmzcKiMg2qL6x0EmQi-20gt0e1121UyoIuHXatm9Y--OPsaB3dFQeMaPUdCe6oQoOV8LL7j5xAS8eeFdsrrqIWHw
[2018-08-14 10:53:07.738] [DEBUG] self-service-manager - request sign up failure
{ Error: Forbidden
    at Request._callback (C:\....\insurance-bot\node_modules\ibmcloud-appid\lib\self-service\self-service-manager.js:269:16)
    at Request.self.callback (C:\...\insurance-bot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\....\insurance-bot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\....\insurance-bot\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20) statusCode: 403, message: 'Forbidden' }
POST /signup 500 6748.472 ms - 35

**Comment by data-henrik** [comment]
That should be in a new issue. Also, don't put any credentials into GitHub issues.

**Comment by spearz** [comment]
Thank you @data-henrik  ok noted
