### ISSUE TITLE
self-service-manager - request sign up failure

### ISSUE THREAD

**Issue by spearz** [IBM-Bluemix/cloudco-insurance#17]
Start the sign up process, to create a Cloud Directory user  i get  self-service-manager - request sign up failure(Error code 403) after  Obtained IAM token 

PS C:\..\insurance-bot> npm start

> CloudCo@0.0.1 start C:\...\insurance-bot
> node app.js

[2018-08-14 10:51:35.306] [DEBUG] appid-public-key-util - Initializing
[2018-08-14 10:51:36.068] [DEBUG] appid-token-util - Initializing
[2018-08-14 10:51:36.201] [INFO] appid-sdk - Initialized
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
[2018-08-14 10:51:37.279] [DEBUG] appid-webapp-strategy - Initializing
[2018-08-14 10:51:37.280] [DEBUG] appid-webapp-strategy-config - Initializing
[2018-08-14 10:51:37.280] [INFO] appid-webapp-strategy-config - tenantId e2
[2018-08-14 10:51:37.280] [INFO] appid-webapp-strategy-config - clientId 87
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - secret [NOT SHOWING]
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - oauthServerUrl https://appid-oauth.eu-gb.bluemix.net/oauth/v3/e2
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - redirectUri http://localhost:6001/health
[2018-08-14 10:51:37.281] [INFO] appid-webapp-strategy-config - preferredLocale undefined
[2018-08-14 10:51:37.282] [INFO] self-service-manager - using user IAM API key [NOT SHOWING]
[2018-08-14 10:51:37.282] [INFO] self-service-manager - iamTokenUrl https://iam.bluemix.net/oidc/token
[2018-08-14 10:51:37.283] [INFO] self-service-manager - managementUrl https://appid-management.eu-gb.bluemix.net/management/v4/e2
server starting on http://localhost:6001
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
{ url: 'https://gateway.watsonplatform.net/assistant/api',
  username: '0f',
  password: 'te' }
No conversation workspace configured in the environment.
Looking for a workspace named 'Ana'...
Loaded local VCAP { services:
   { cloudantNoSQLDB: [ [Object] ],
     conversation: [ [Object] ],
     AppID: [ [Object] ] } }
Database already exists:  logs
Database already exists:  benefits
Using Watson Conversation with username 0f and workspace 09
GET /health 200 310.081 ms - 3002
GET /isLoggedIn 200 2.558 ms - 27
GET /favicon.ico 404 4.247 ms - 150
GET /signup 200 46.224 ms - 3145
GET /isLoggedIn 304 1.400 ms - -
[2018-08-14 10:53:06.092] [DEBUG] self-service-manager - Obtained IAM token: exq
[2018-08-14 10:53:07.738] [DEBUG] self-service-manager - request sign up failure
{ Error: Forbidden
    at Request._callback (C:\....\insurance-bot\node_modules\ibmcloud-appid\lib\self-service\self-service-manager.js:269:16)
    at Request.self.callback (C:\...\insurance-bot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\....\insurance-bot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\....\insurance-bot\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20) statusCode: 403, message: 'Forbidden' }
POST /signup 500 6748.472 ms - 35

**Comment by spearz** [comment]
Hello @data-henrik ,

Did i format it well? Still stuck on the same issue. 

Thank you for your assistance.
Regards,
Matimu Ignatius

**Comment by data-henrik** [comment]
You seem to use a local environment, not the cloud deployment. What steps did you follow?
Did you apply the appid-config.json as done in https://github.com/IBM-Cloud/insurance-bot/blob/dev/.bluemix/pipeline-DEPLOY.sh ?

**Comment by spearz** [comment]
@data-henrik thank you for the reply 

Yes i thought of running app locally. Steps used are for local deployment also both appid-config.json and pipeline-DEPLOY.sh are the same. 

Let me attempt cloud

**Comment by spearz** [comment]
Hello @data-henrik  

I started all over again it worked deployed on the cloud. 

Thank you

**Comment by data-henrik** [comment]
Ok, good to know. Closing this issue.
